# FTP deploy Hexo based site using Travis-ci.org
# https://gist.github.com/HoverBaum/524528aec1032b29669fe9cc82dba066
#
# 1. Copy this file to the root of your repository, then rename it to '.travis.yml'
# 2. Replace 'YOUR NAME' and 'YOUR EMAIL'
# 3. Create "Environment Variables" in travis. Make sure to not show them in the output.
#     - FTP_USER: The username for FTP transfer.
#     - FTP_PASSWORD: Password for the user.
# 4. Replace "DOMAIN.TLD" with your FTP domain and maybe the path where to put things.
#
# This should also work with other static site generators. Just replace hexo
# with your generator.

language: node_js

node_js:
- "6"

branches:
  only:
  - master

before_install:
- npm install -g hexo

install:
- npm install

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
- git config --global user.name 'hoverbaum'
- git config --global user.email 'mail@hendrikwallbaum.de'

script:
- hexo generate #generate site

# Upload site using FTP.
# -exec must be closed with ";" which must be escaped (hence the "s).
# Finds all files and calls curl to upload them for every file.
after_success:
    'find public -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://hoverbaum.net/{} ";"'
